services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teasoc-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
    ports:
      - "8081:8081"
    networks:
      - teasoc-net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - teasoc-net
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  teasoc-net:
    driver: bridge
